endofcode = "###############################################################"
# Sandbox Starts here
print(endofcode)
print(2 // 3)
print(2 // 3.)
print(2. // 3)
print(2. // 3.)
print(6 // 4)
print(6. // 4)
print(-6 // 4)
print(6. // -4)
print(endofcode)
print(12 % 5)
print(12 % 4.5)
print(9 % 3)
print(endofcode)